#!/usr/bin/env bash
bashop::init() {
  bashop::logger::info "init: ${BASHOP_ROOT}";
}

bashop::destroy() {
  bashop::logger::info "destroy: ${BASHOP_ROOT}";
}

readonly BASHOP_APP_NAME='exampleapp'

source "../src/bashop/bootstrap.sh"