#!/usr/bin/env bash
bashop::init() {
  bashop::logger::info "init: ${_BASHOP_ROOT}";
}

bashop::destroy() {
  bashop::logger::info "destroy: ${_BASHOP_ROOT}";
}

_BASHOP_APP_NAME='exampleapp'

source "../src/bashop/bootstrap.sh"