#!/usr/bin/env bash

#?d The example command
#?c --coption -z <name> <version> [<extra>...]
#?o -a  Short option
#?o -b --boption  Short and long option.
#?o -r..., --roption...  A repeatable option with shortcut.
#?o -x... <arg>, --xoption...=<arg>  A repeatable option with requrired argument.
#?o -y... <arg>, --yoption...=<arg>  A repeatable option with requrired argument [default: test].

bashop::run_command() {
  echo "---- Args -----"

  for key in "${!args[@]}"; do
    k=$(echo ${key} | grep -o '[a-z0-9\<\>\-]*')


    if [[ $(echo ${key} | grep -o '[\#]*') == "#" ]] && (bashop::utils::key_exists "${k},#" args); then
      echo "|> ${k} R"

      if [[ ${args["${k},#"]} -eq 0 ]]; then
        echo "|==> NOT SET"
      else
        local i=0
        while [[ ${i} -lt ${args["${k},#"]} ]] ; do
          echo "|==> ${args[${k},${i}]}"
          i=$[${i}+1]
        done
      fi
    elif [[ -z $(echo ${key} | grep -o '[\,]*') ]]; then
      echo "|> ${k} S"

      if [[ -n ${args[${k}]} ]]; then
        echo "|==> ${args[${k}]}"
      else
        echo "|==> NOT SET"
      fi
    fi
  done
}

