#!/usr/bin/env bash

#?d The example command
#?c --test -z <name> <version> [<extra>...]
#?o -a  Test
#?o -g --ver  Test
#?o --option  An optional option.
#?o --repeatable...  A repeatable option.
#?o -o, --optional-opt  An optional option with shortcut.
#?o -r..., --repeatable-opt...  A repeatable option with shortcut.
#?o -a ARG, --argument-opt=<arg>  A required option with optional argument [default: test].
#?o -b... <arg>, --bbb...=<arg>  A required option with requrired argument.
#?o -c... SARG --output...=<arg>  Aaaa [default: test].
#?o -d <sarg> --dee LARG  Aaaa [default: test].
#?o -e <sarg> --eee LARG  Aaaa.

BASHOP_COMMAND_DESCRIPTION="The example command"

bashop::run_command() {
  echo "---- Args -----"

  for key in "${!args[@]}"; do
    k=$(echo ${key} | grep -o '[a-z0-9\<\>\-]*')


    if [[ $(echo ${key} | grep -o '[\#]*') == "#" ]] && (bashop::utils::key_exists "${k},#" args); then
      echo "|> ${k} R"

      if [[ ${args["${k},#"]} -eq 0 ]]; then
        echo "|==> NOT SET"
      else
        local i=0
        while [[ ${i} -lt ${args["${k},#"]} ]] ; do
          echo "|==> ${args[${k},${i}]}"
          i=$[${i}+1]
        done
      fi
    elif [[ -z $(echo ${key} | grep -o '[\,]*') ]]; then
      echo "|> ${k} S"

      if [[ -n ${args[${k}]} ]]; then
        echo "|==> ${args[${k}]}"
      else
        echo "|==> NOT SET"
      fi
    fi
  done
}

