#!/usr/bin/env bash

#test
commands=(
  'com'
)

command_arguments=(
  "name"
  "version"
)

declare -g -A command_options=(
  ["single-required:"]="A required option"
  ["single-optional?"]="An optional option"
  ["single-repeatable+"]="A repeatable option"
  ["r|required-opt:"]="A required option with shortcut"
  ["o|optional-opt?"]="An optional option with shortcut"
  ["p|repeatable-opt+"]="A repeatable option with shortcut"
  ["a|optional-argument-opt?=test"]="A required option with optional argument"
  ["b|required-argument-opt?="]="A required option with requrired argument"
)

_run() {
  echo "---- Args -----"

  for key in "${!args[@]}"; do
    k=$(echo ${key} | grep -o '[a-z0-9\-]*')


    if [[ $(echo ${key} | grep -o '[\#]*') == "#" ]] && (key_exists "${k},#" args); then
      echo "|> ${k}"

      i=0
      while [[ ${i} -lt ${args["${k},#"]} ]] ; do
        echo "|==> ${args[${k},${i}]}"
        i=$[$i+1]
      done
    elif [[ $(echo ${key} | grep -o '[\,]*') == "" ]]; then
      echo "|> ${k}"
      echo "|==> ${args[${k}]}"
    fi
  done
}

