#!/usr/bin/env bash

#?c --test -z <name> <version> [<extra>...]
#?o -v
#?o --option  An optional option.
#?o --repeatable...  A repeatable option.
#?o -o, --optional-opt  An optional option with shortcut.
#?o -r..., --repeatable-opt...  A repeatable option with shortcut.
#?o -a ARG, --argument-opt=<arg>  A required option with optional argument [default: test].
#?o -b... <arg>, --repeatable-argument-opt...=<arg>  A required option with requrired argument.
#?o -c... SARG --output...=<arg>  Aaaa [default: test].
#?o -d <sarg> --dee LARG  Aaaa [default: test].

BASHOP_COMMAND_DESCRIPTION="The example command"

BASHOP_COMMAND_ARGUMENTS=(
  "name"
  "version"
)

declare -g -A BASHOP_COMMAND_OPTIONS=(
  ["single-required:"]="A required option"
  ["single-optional?"]="An optional option"
  ["single-repeatable+"]="A repeatable option"
  ["r|required-opt:"]="A required option with shortcut"
  ["o|optional-opt?"]="An optional option with shortcut"
  ["p|repeatable-opt+=<arg>"]="A repeatable option with shortcut"
  ["a|optional-argument-opt?=<arg:test>"]="A required option with optional argument"
  ["b|required-argument-opt?=<arg>"]="A required option with requrired argument"
)

bashop::run_command() {
  echo "---- Args -----"

  for key in "${!args[@]}"; do
    k=$(echo ${key} | grep -o '[a-z0-9\-]*')


    if [[ $(echo ${key} | grep -o '[\#]*') == "#" ]] && (bashop::utils::key_exists "${k},#" args); then
      echo "|> ${k}"

      i=0
      while [[ ${i} -lt ${args["${k},#"]} ]] ; do
        echo "|==> ${args[${k},${i}]}"
        i=$[${i}+1]
      done
    elif [[ -z $(echo ${key} | grep -o '[\,]*') ]]; then
      echo "|> ${k}"
      echo "|==> ${args[${k}]}"
    fi
  done
}

